import { chromium } from "playwright-core";
import { execSync } from "child_process";
const EXE = execSync("ls -d /opt/pw-browsers/chromium*/chrome-linux/chrome 2>/dev/null | head -1").toString().trim();
const SHOT = process.env.SHOT_DIR, BASE = process.env.BASE || "http://localhost:3915";
const b = await chromium.launch({ executablePath: EXE, args: ["--no-sandbox"] });
const p = await (await b.newContext({ viewport: { width: 1440, height: 950 } })).newPage();
await p.goto(`${BASE}/`, { waitUntil: "networkidle" }); await p.waitForTimeout(1000);
const ta = p.locator("textarea").first();
await ta.fill("What should I check first for PowerFlex 525 F004?"); await ta.press("Enter");
await p.waitForTimeout(5000);
await p.screenshot({ path: `${SHOT}/T-copilot.png` });
await p.goto(`${BASE}/dashboard`, { waitUntil: "networkidle" }); await p.waitForTimeout(1500);
await p.screenshot({ path: `${SHOT}/T-dashboard.png` });
await b.close(); console.log("theme shots done");
